### ISSUE TITLE
NumberFormatException in ArcheryRange.onLoggedOut

### ISSUE THREAD

**Issue by nhnb** [arianne/stendhal#210]
~~~~
java.lang.NumberFormatException: null
	at java.lang.Integer.parseInt(Integer.java:542)
	at java.lang.Integer.parseInt(Integer.java:615)
	at games.stendhal.server.maps.nalwor.forest.ArcheryRange$Timer.<init>(ArcheryRange.java:486)
	at games.stendhal.server.maps.nalwor.forest.ArcheryRange.onLoggedOut(ArcheryRange.java:443)
	at games.stendhal.server.core.events.LogoutNotifier.onPlayerLoggedOut(LogoutNotifier.java:80)
	at games.stendhal.server.core.engine.StendhalRPRuleProcessor.onLogout(StendhalRPRuleProcessor.java:584)
	at games.stendhal.server.core.engine.StendhalRPRuleProcessor.onTimeout(StendhalRPRuleProcessor.java:598)
	at marauroa.server.game.rp.RPServerManager.onTimeout(RPServerManager.java:479)
	at marauroa.server.game.messagehandler.DisconnectHandler.handleDelayedEvent(DisconnectHandler.java:56)
	at marauroa.server.game.messagehandler.DelayedEventHandlerThread.run(DelayedEventHandlerThread.java:100)
~~~~

**Comment by AntumDeluge** [comment]
Should be fixed now in 1b8acda.

**Comment by tigertoes13** [comment]
did a pull, so i am assuming my setup is current, barring files i have changed, which have nothing to do with this problem... so, i am still getting the following.
java.lang.NumberFormatException: For input string: "1541677804822"
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at games.stendhal.server.maps.nalwor.forest.ArcheryRange$Timer.<init>(ArcheryRange.java:486)
	at games.stendhal.server.maps.nalwor.forest.ArcheryRange.onLoggedOut(ArcheryRange.java:443)
	at games.stendhal.server.core.events.LogoutNotifier.onPlayerLoggedOut(LogoutNotifier.java:80)
	at games.stendhal.server.core.engine.StendhalRPRuleProcessor.onLogout(StendhalRPRuleProcessor.java:584)
	at games.stendhal.server.core.engine.StendhalRPRuleProcessor.onExit(StendhalRPRuleProcessor.java:556)
	at marauroa.server.game.rp.RPServerManager.onExit(RPServerManager.java:470)
	at marauroa.server.game.messagehandler.LogoutHandler.process(LogoutHandler.java:75)
	at marauroa.server.game.messagehandler.MessageDispatcher.dispatchMessage(MessageDispatcher.java:112)
	at marauroa.server.game.GameServerManager.run(GameServerManager.java:271)

**Comment by tigertoes13** [comment]
forgot to mention that when penelaine logs out, there is no issue, and she has not done anything with archeryrange... however tigertoes has.

**Comment by AntumDeluge** [comment]
Okay. I will have another look at it.

**Comment by nhnb** [comment]
Archery ranges has been removed for now (the code, not the map)
